import type { Metadata } from "next";
import { ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { PageIntro } from "@/components/ui/page-intro";
import { Reveal } from "@/components/ui/reveal";
import { approachSteps } from "@/config/site";
export const metadata: Metadata = { title: "My Approach", description: "Souvik Saha's practical process for social media management, digital marketing, and business promotion." };
export default function ApproachPage() { return <SiteShell><PageIntro eyebrow="My approach" title="A calm process for building real marketing momentum." description="The work is structured to reduce guesswork, make decisions easier, and leave your business with a more useful way to show up online." /><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><Reveal className="grid gap-8 border-b border-[#d9d8d0] pb-10 lg:grid-cols-[.65fr_1.35fr]"><p className="eyebrow text-[#ca5b43]">The process / 01—06</p><p className="max-w-2xl text-lg leading-8 text-[#59645d]">No two businesses start in exactly the same place. The process creates enough structure to move forward with confidence while staying responsive to the realities of your market and audience.</p></Reveal><div>{approachSteps.map((step, index) => <Reveal key={step.number} delay={index * .06} className="grid gap-5 border-b border-[#d9d8d0] py-8 sm:grid-cols-[100px_1fr_1fr] sm:gap-8"><p className="eyebrow text-[#ca5b43]">{step.number}</p><h2 className="display text-4xl leading-none sm:text-5xl">{step.title}</h2><p className="max-w-md text-sm leading-6 text-[#68716b]">{step.copy}</p></Reveal>)}</div></div></section><section className="bg-[#18211d] px-5 py-20 text-[#f7f6f1] sm:px-8 lg:px-12"><Reveal className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#d8e5a4]">A more useful partnership</p><h2 className="display mt-5 text-5xl leading-[.95]">Clear on what matters. Flexible where it counts.</h2></div><p className="max-w-xl self-end text-lg leading-8 text-white/60">The purpose of the process is not to add ceremony. It is to ensure that content, campaigns, and promotion keep serving the business rather than becoming a separate stream of activity.</p></Reveal></section><section className="px-5 py-20 text-center sm:px-8 lg:px-12"><Reveal><p className="eyebrow text-[#ca5b43]">Start with the first conversation</p><Link href="/contact" className="display mt-4 inline-flex items-center gap-3 text-4xl hover:text-[#ca5b43] sm:text-5xl">Let&apos;s talk about your next step <ArrowUpRight size={24} /></Link></Reveal></section></SiteShell>; }
