import { ArrowDownRight, ArrowUpRight, Blocks, Instagram, Megaphone, Search } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { Reveal } from "@/components/ui/reveal";
import { approachSteps, homePrinciples, serviceGroups, services } from "@/config/site";

export function HomeExperience() {
  const buildServices = services.filter((service) => service.group === "Build");
  const growServices = services.filter((service) => service.group === "Grow");
  return <SiteShell>
    <section className="grain px-5 pb-16 pt-36 sm:px-8 lg:px-12 lg:pb-24 lg:pt-44"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><Reveal><p className="eyebrow text-[#ca5b43]">Souvik Saha / Digital Development & Growth</p><h1 className="display mt-6 max-w-4xl text-balance text-[clamp(3.75rem,8vw,8.25rem)] leading-[.84] text-[#18211d]">I build the digital presence—<em className="font-normal text-[#ca5b43]">and help it grow.</em></h1><p className="mt-8 max-w-xl text-pretty text-lg leading-8 text-[#59645d]">I&apos;m Souvik Saha. I develop websites and digital products, then help the businesses behind them grow through social media, digital marketing, and thoughtful online promotion.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/work" className="inline-flex items-center gap-2 bg-[#18211d] px-5 py-3.5 text-sm font-bold text-white transition-colors hover:bg-[#ca5b43]">View my work <ArrowDownRight size={16} /></Link><Link href="/contact" className="inline-flex items-center gap-2 border border-[#18211d] px-5 py-3.5 text-sm font-bold text-[#18211d] transition-colors hover:bg-[#e8e9de]">Let&apos;s work together <ArrowUpRight size={16} /></Link></div></Reveal><Reveal delay={.15} className="relative mx-auto w-full max-w-[470px] lg:ml-auto"><div className="aspect-[.95] border border-[#d9d8d0] bg-[#e6e7df] p-5 sm:p-7"><div className="flex h-full flex-col justify-between border border-[#18211d]/20 p-5 sm:p-7"><div className="flex items-center justify-between"><span className="eyebrow text-[#18211d]/55">Souvik Saha</span><span className="size-3 rounded-full bg-[#ca5b43]" /></div><div className="relative"><span className="absolute -left-2 -top-7 text-7xl leading-none text-[#ca5b43]">“</span><p className="display relative z-10 max-w-xs text-4xl leading-[.95] text-[#18211d] sm:text-5xl">Build what matters. Grow what works.</p></div><div className="flex items-center justify-between border-t border-[#18211d]/15 pt-4 text-xs font-bold uppercase tracking-[.12em] text-[#59645d]"><span>Build / Grow</span><span>01—02</span></div></div></div><div className="absolute -bottom-5 -left-5 border border-[#d9d8d0] bg-[#f7f6f1] p-4 shadow-[0_12px_25px_rgba(24,33,29,.09)]"><div className="flex items-center gap-2 text-xs font-bold text-[#18211d]"><span className="size-2 rounded-full bg-[#ca5b43]" />From concept to momentum</div><div className="mt-3 flex gap-2 text-[#59645d]"><Blocks size={17} /><Instagram size={17} /><Search size={17} /></div></div></Reveal></div></section>
    <section className="border-y border-[#d9d8d0] bg-[#e8e9de] px-5 py-5 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-wrap justify-between gap-4 text-xs font-bold uppercase tracking-[.13em] text-[#59645d]"><span>Website development</span><span>Web applications</span><span>Social media management</span><span>Digital marketing</span></div></section>
    <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1440px]"><Reveal className="grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><p className="eyebrow text-[#ca5b43]">What I do</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95] sm:text-6xl">Two sides of one useful digital practice.</h2></div><p className="max-w-2xl self-end text-lg leading-8 text-[#59645d]">A business needs more than attention online. It needs something clear and useful for that attention to arrive at. I work across both: the digital foundation and the growth around it.</p></Reveal><div className="mt-14 grid gap-px border-y border-[#d9d8d0] bg-[#d9d8d0] lg:grid-cols-2">{serviceGroups.map((group, index) => { const Icon = group.icon; const groupServices = group.name === "Build" ? buildServices : growServices; return <Reveal key={group.name} delay={index * .08} className={`bg-[#f7f6f1] p-7 sm:p-10 ${group.name === "Grow" ? "bg-[#e8e9de]" : ""}`}><Icon size={23} strokeWidth={1.4} className="text-[#ca5b43]" /><p className="eyebrow mt-10 text-[#ca5b43]">{group.eyebrow}</p><h3 className="display mt-4 text-5xl leading-[.95]">{group.title}</h3><p className="mt-5 max-w-md text-base leading-7 text-[#68716b]">{group.copy}</p><ul className="mt-10 grid gap-3 border-t border-[#c9cac2] pt-5 text-sm text-[#59645d]">{groupServices.map((service) => <li key={service.slug} className="flex items-center justify-between gap-3"><span>{service.title}</span><Link href={`/${service.slug}`} aria-label={`Learn about ${service.title}`} className="text-[#ca5b43] hover:text-[#18211d]"><ArrowUpRight size={15} /></Link></li>)}</ul></Reveal>; })}</div></div></section>
    <section className="border-y border-[#d9d8d0] bg-[#e8e9de] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="eyebrow text-[#ca5b43]">Selected work</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95] sm:text-6xl">Work is shared in the context that makes it useful.</h2></Reveal><Reveal delay={.08} className="grid content-center gap-6"><p className="max-w-2xl text-lg leading-8 text-[#59645d]">I work across digital development and growth projects for businesses that need a stronger place to show up online—and a considered way to build momentum around it.</p><Link href="/work" className="inline-flex w-fit items-center gap-2 text-sm font-bold text-[#18211d] hover:text-[#ca5b43]">Explore the work <ArrowUpRight size={16} /></Link></Reveal></div></section>
    <section className="bg-[#18211d] px-5 py-24 text-[#f7f6f1] sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1440px]"><Reveal><p className="eyebrow text-[#d8e5a4]">How I work</p><div className="mt-5 flex flex-col justify-between gap-7 md:flex-row md:items-end"><h2 className="display max-w-2xl text-5xl leading-[.95] sm:text-6xl">A clear path from the first idea to what comes after launch.</h2><Link href="/approach" className="inline-flex items-center gap-2 text-sm font-bold text-[#d8e5a4] hover:text-white">Explore my approach <ArrowUpRight size={16} /></Link></div></Reveal><div className="mt-14 grid divide-y divide-white/15 border-y border-white/15 md:grid-cols-3 md:divide-x md:divide-y-0">{approachSteps.slice(0, 3).map((step, index) => <Reveal key={step.number} delay={index * .1} className="px-0 py-8 md:px-7 md:first:pl-0"><p className="eyebrow text-[#d8e5a4]">{step.number}</p><h3 className="display mt-10 text-4xl">{step.title}</h3><p className="mt-4 max-w-xs text-sm leading-6 text-white/60">{step.copy}</p></Reveal>)}</div></div></section>
    <section className="border-y border-[#d9d8d0] bg-[#e8e9de] px-5 py-24 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="eyebrow text-[#ca5b43]">About Souvik Saha</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95] sm:text-6xl">A digital professional with both sides in view.</h2><Link href="/about" className="mt-8 inline-flex items-center gap-2 text-sm font-bold hover:text-[#ca5b43]">More about my work <ArrowUpRight size={16} /></Link></Reveal><Reveal delay={.08} className="grid content-center gap-6 text-lg leading-8 text-[#59645d]"><p>I develop websites, web applications, and digital experiences that give businesses a stronger place to show up online.</p><p>I also work on the marketing around that presence: social media, content, promotion, and the digital activity that helps the right people find it.</p></Reveal></div></section>
    <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.68fr_1.32fr]"><Reveal><p className="eyebrow text-[#ca5b43]">Services & capabilities</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95] sm:text-6xl">Build the foundation. Grow the momentum.</h2><Link href="/services" className="mt-8 inline-flex items-center gap-2 text-sm font-bold hover:text-[#ca5b43]">Explore all services <ArrowUpRight size={16} /></Link></Reveal><div className="grid border-t border-[#d9d8d0] md:grid-cols-3">{homePrinciples.map((principle, index) => { const Icon = principle.icon; return <Reveal key={principle.title} delay={index * .08} className="border-b border-[#d9d8d0] py-7 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><Icon size={20} strokeWidth={1.5} className="text-[#ca5b43]" /><h3 className="mt-12 text-xl font-semibold tracking-[-.035em]">{principle.title}</h3><p className="mt-3 text-sm leading-6 text-[#68716b]">{principle.copy}</p></Reveal>; })}</div></div></section>
    <section className="px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><Reveal className="mx-auto max-w-[1440px] border-y border-[#d9d8d0] py-14 text-center sm:py-20"><Megaphone size={22} strokeWidth={1.5} className="mx-auto text-[#ca5b43]" /><p className="eyebrow mt-6 text-[#ca5b43]">Start a conversation</p><h2 className="display mx-auto mt-5 max-w-3xl text-balance text-5xl leading-[.95] sm:text-7xl">Have something to build—or a business ready to grow?</h2><p className="mx-auto mt-6 max-w-xl text-lg leading-8 text-[#68716b]">Let&apos;s talk about the website, product, social presence, or marketing work that can give your next step more momentum.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-2 bg-[#18211d] px-5 py-3.5 text-sm font-bold text-white hover:bg-[#ca5b43]">Let&apos;s work together <ArrowUpRight size={16} /></Link></Reveal></section>
  </SiteShell>;
}
