import type { Metadata } from "next";
import { ArrowUpRight, BarChart3, CalendarDays, HeartHandshake, Lightbulb, Send, TrendingUp } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { PageIntro } from "@/components/ui/page-intro";
import { Reveal } from "@/components/ui/reveal";
import { platformPlaybook } from "@/config/site";
export const metadata: Metadata = { title: "Social Media Management", description: "Professional Instagram, Facebook, and Google social media management for startups and growing businesses." };
const stages = [{ icon: Lightbulb, title: "Strategy", copy: "A focused direction built around your business, audience, message, and the role each platform should play." }, { icon: CalendarDays, title: "Content planning", copy: "A practical content calendar with the right balance of brand-building, useful information, and promotional moments." }, { icon: Send, title: "Platform management", copy: "Publishing and day-to-day presence handled with care, consistency, and respect for each platform's context." }, { icon: HeartHandshake, title: "Community engagement", copy: "A thoughtful approach to audience interaction that supports trust, relevance, and stronger customer relationships." }, { icon: TrendingUp, title: "Growth", copy: "Organic and campaign-led activities designed to increase meaningful reach, visibility, and audience quality." }, { icon: BarChart3, title: "Analytics & optimization", copy: "Regular review of the signals that matter, followed by clear refinements to improve the next cycle." }];
export default function SocialMediaManagementPage() { return <SiteShell><PageIntro eyebrow="Core service / 01" title="Social media with a clearer role in your growth." description="A considered social media management service for businesses that want to show up more consistently, communicate more clearly, and make every interaction count." /><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><Reveal className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#ca5b43]">The scope</p><h2 className="display mt-5 text-5xl leading-[.95]">A full social rhythm—without the noise.</h2></div><p className="max-w-2xl self-end text-lg leading-8 text-[#59645d]">Social media works best when every moving part is connected. Strategy informs content; content creates opportunities for engagement; insight makes the next decision sharper.</p></Reveal><div className="mt-14 grid border-t border-[#d9d8d0] md:grid-cols-2 lg:grid-cols-3">{stages.map((stage, index) => { const Icon = stage.icon; return <Reveal key={stage.title} delay={index * .06} className="border-b border-[#d9d8d0] p-7 md:odd:border-r md:lg:border-r lg:nth-[3n]:border-r-0"><Icon size={20} strokeWidth={1.4} className="text-[#ca5b43]" /><h3 className="mt-12 text-xl font-semibold tracking-[-.035em]">{stage.title}</h3><p className="mt-3 text-sm leading-6 text-[#68716b]">{stage.copy}</p></Reveal>; })}</div></div></section><section className="bg-[#18211d] px-5 py-20 text-[#f7f6f1] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><Reveal><p className="eyebrow text-[#d8e5a4]">Platform-specific thinking</p><h2 className="display mt-5 max-w-3xl text-5xl leading-[.95] sm:text-6xl">Different platforms. One coherent business presence.</h2></Reveal><div className="mt-14 grid divide-y divide-white/15 border-y border-white/15 md:grid-cols-3 md:divide-x md:divide-y-0">{platformPlaybook.map((platform, index) => { const Icon = platform.icon; return <Reveal key={platform.title} delay={index * .08} className="p-7 first:pl-0"><Icon size={20} strokeWidth={1.4} className="text-[#d8e5a4]" /><p className="eyebrow mt-10 text-white/45">{platform.descriptor}</p><h3 className="display mt-3 text-4xl">{platform.title}</h3><p className="mt-4 text-sm leading-6 text-white/60">{platform.copy}</p></Reveal>; })}</div></div></section><section className="px-5 py-20 sm:px-8 lg:px-12"><Reveal className="mx-auto flex max-w-[1440px] flex-col justify-between gap-6 border-y border-[#d9d8d0] py-14 md:flex-row md:items-center"><div><p className="eyebrow text-[#ca5b43]">Need a better social system?</p><h2 className="display mt-4 text-4xl leading-[.95] sm:text-5xl">Let&apos;s discuss what your business needs.</h2></div><Link href="/contact" className="inline-flex shrink-0 items-center gap-2 bg-[#18211d] px-5 py-3.5 text-sm font-bold text-white hover:bg-[#ca5b43]">Let&apos;s Talk <ArrowUpRight size={16} /></Link></Reveal></section></SiteShell>; }
