import type { Metadata } from "next";
import { ArrowUpRight, Check } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { PageIntro } from "@/components/ui/page-intro";
import { Reveal } from "@/components/ui/reveal";
import { serviceGroups, services } from "@/config/site";

export const metadata: Metadata = { title: "Services", description: "Web development, web applications, backend integration, social media management, digital marketing, and business growth services by Souvik Saha." };
export default function ServicesPage() { return <SiteShell><PageIntro eyebrow="Services" title="Build the digital presence. Grow the business behind it." description="Two connected areas of work for startups, businesses, and growing brands: the digital products people use, and the marketing that helps the right people find them." /><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px] space-y-24">{serviceGroups.map((group, groupIndex) => { const Icon = group.icon; const groupServices = services.filter((service) => service.group === group.name); return <section key={group.name}><Reveal className={`grid gap-8 border-y border-[#d9d8d0] py-8 lg:grid-cols-[.55fr_1.45fr] ${group.name === "Grow" ? "bg-[#e8e9de] -mx-5 px-5 sm:-mx-8 sm:px-8 lg:-mx-12 lg:px-12" : ""}`}><div><Icon size={21} strokeWidth={1.4} className="text-[#ca5b43]" /><p className="eyebrow mt-5 text-[#ca5b43]">{group.eyebrow}</p></div><div><h2 className="display text-5xl leading-[.95] sm:text-6xl">{group.title}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[#68716b]">{group.copy}</p></div></Reveal><div>{groupServices.map((service, index) => { const ServiceIcon = service.icon; return <Reveal key={service.slug} delay={(groupIndex * .04) + (index * .05)} className="grid gap-7 border-b border-[#d9d8d0] py-10 lg:grid-cols-[.35fr_.95fr_1fr_.3fr]"><div><ServiceIcon size={22} strokeWidth={1.4} className="text-[#ca5b43]" /><p className="eyebrow mt-6 text-[#68716b]">{service.label}</p></div><div><h3 className="display text-4xl leading-[.95] sm:text-5xl">{service.title}</h3><p className="mt-5 max-w-md text-sm leading-6 text-[#68716b]">{service.description}</p></div><ul className="grid content-start gap-3 text-sm text-[#59645d]">{service.deliverables.map((item) => <li key={item} className="flex gap-2"><Check size={15} className="mt-.5 shrink-0 text-[#ca5b43]" />{item}</li>)}</ul><Link href={`/${service.slug}`} className="group inline-flex size-10 items-center justify-center self-start border border-[#18211d] transition-colors hover:bg-[#18211d] hover:text-white" aria-label={`Learn about ${service.title}`}><ArrowUpRight size={16} /></Link></Reveal>; })}</div></section>; })}</div></section><section className="border-y border-[#d9d8d0] bg-[#e8e9de] px-5 py-20 sm:px-8 lg:px-12"><Reveal className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow text-[#ca5b43]">How engagements work</p><h2 className="display mt-5 max-w-md text-5xl leading-[.95]">The right work starts with the right side of the problem.</h2></div><p className="max-w-xl self-end text-lg leading-8 text-[#59645d]">Some businesses need a new digital foundation. Others need more visibility around the one they already have. Many benefit from both. The scope begins with what will create the most useful momentum now.</p></Reveal></section></SiteShell>; }
