import type { Metadata } from "next";
import { ArrowUpRight, BarChart3, Crosshair, Megaphone, MessageSquareText, MousePointerClick, Radar } from "lucide-react";
import Link from "next/link";
import { SiteShell } from "@/components/layout/site-shell";
import { PageIntro } from "@/components/ui/page-intro";
import { Reveal } from "@/components/ui/reveal";
export const metadata: Metadata = { title: "Digital Marketing & Promotion", description: "Campaign strategy, online promotion, audience targeting, and performance analysis for businesses and startups." };
const offerings = [{ icon: Crosshair, title: "Campaign strategy", copy: "Define what the campaign needs to accomplish, who it needs to reach, and the message that gives it a reason to land." }, { icon: MessageSquareText, title: "Promotion planning", copy: "Plan the content, timing, channels, and calls-to-action that turn a good idea into a focused promotional effort." }, { icon: Radar, title: "Audience targeting", copy: "Shape activity around a more relevant audience, rather than simply broadening the message and hoping it travels." }, { icon: MousePointerClick, title: "Conversion focus", copy: "Create clearer paths from attention to enquiry, visit, sign-up, or the next useful action for the business." }, { icon: Megaphone, title: "Campaign delivery", copy: "Run promotional activity with a steady operating rhythm and thoughtful coordination between channels." }, { icon: BarChart3, title: "Performance analysis", copy: "Review what worked, what needs attention, and how the next campaign can make better use of budget and effort." }];
export default function DigitalMarketingPage() { return <SiteShell><PageIntro eyebrow="Core service / 02" title="Promotion that gives your message somewhere to go." description="Digital marketing support for businesses that need sharper campaigns, stronger audience relevance, and a more deliberate connection between attention and action." /><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><Reveal className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#ca5b43]">What it includes</p><h2 className="display mt-5 text-5xl leading-[.95]">Promotion with a proper point of view.</h2></div><p className="max-w-2xl self-end text-lg leading-8 text-[#59645d]">Effective campaigns make it easier for the right people to understand why your business is relevant to them—then make the next step feel straightforward.</p></Reveal><div className="mt-14 grid gap-px bg-[#d9d8d0] md:grid-cols-2 lg:grid-cols-3">{offerings.map((offering, index) => { const Icon = offering.icon; return <Reveal key={offering.title} delay={index * .06} className="bg-[#f7f6f1] p-7"><Icon size={20} strokeWidth={1.4} className="text-[#ca5b43]" /><h3 className="mt-12 text-xl font-semibold tracking-[-.035em]">{offering.title}</h3><p className="mt-3 text-sm leading-6 text-[#68716b]">{offering.copy}</p></Reveal>; })}</div></div></section><section className="border-y border-[#d9d8d0] bg-[#e8e9de] px-5 py-20 sm:px-8 lg:px-12"><Reveal className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-2"><div><p className="eyebrow text-[#ca5b43]">For startups & growing businesses</p><h2 className="display mt-5 max-w-lg text-5xl leading-[.95]">The campaign should fit the stage you&apos;re in.</h2></div><div className="grid content-end gap-5 text-base leading-7 text-[#59645d]"><p>Launch activity, awareness work, local promotion, and ongoing digital campaigns all ask different things of a business. The work starts by understanding that context.</p><p>No inflated promises. No activity for activity&apos;s sake. Just a useful plan, carefully delivered and actively reviewed.</p></div></Reveal></section><section className="px-5 py-20 sm:px-8 lg:px-12"><Reveal className="mx-auto max-w-[1440px] border-y border-[#d9d8d0] py-14 text-center"><p className="eyebrow text-[#ca5b43]">Have a campaign in mind?</p><h2 className="display mx-auto mt-5 max-w-2xl text-5xl leading-[.95]">Let&apos;s give it a stronger strategy.</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-[#18211d] px-5 py-3.5 text-sm font-bold text-white hover:bg-[#ca5b43]">Start a conversation <ArrowUpRight size={16} /></Link></Reveal></section></SiteShell>; }
